//! Numerical parity against the HuggingFace CodeGen reference implementation.
//!
//! Fixtures are tiny randomly-initialised models generated by
//! `scripts/gen_parity_fixture.py` and committed under `tests/fixtures/`, so this
//! test needs no model download and no Python.

use std::path::Path;

use candle_core::Device;
use rust_transformer::codegen::config::CodeGenConfig;
use rust_transformer::codegen::kv_cache::KVCache;
use rust_transformer::codegen::model::CodeGenModel;
use rust_transformer::codegen::weights::WeightLoader;
use rust_transformer::generation::codegen_generate::CodeGenGenerator;

struct Fixture {
    config: CodeGenConfig,
    model: CodeGenModel,
    tokens: Vec<u32>,
    reference: Vec<f32>,
    shape: Vec<usize>,
}

fn load(name: &str) -> Fixture {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let device = Device::Cpu;

    let config_json: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join(format!("{name}_config.json")))
            .expect("fixture config missing — run scripts/gen_parity_fixture.py"),
    )
    .expect("fixture config is not valid JSON");
    let config = CodeGenConfig::from_hf_config(&config_json);

    let model = WeightLoader::load_from_pytorch(&dir.join(format!("{name}.pth")), &config, &device)
        .expect("failed to load fixture weights");

    let logits_json: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join(format!("{name}_logits.json")))
            .expect("fixture logits missing"),
    )
    .expect("fixture logits are not valid JSON");

    let tokens: Vec<u32> = logits_json["tokens"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as u32)
        .collect();
    let reference: Vec<f32> = logits_json["logits"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    let shape: Vec<usize> = logits_json["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    Fixture {
        config,
        model,
        tokens,
        reference,
        shape,
    }
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "logit count mismatch");
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn assert_prefill_matches_reference(name: &str) {
    let f = load(name);
    let positions: Vec<usize> = (0..f.tokens.len()).collect();

    let logits = f
        .model
        .forward_with_cache(&f.tokens, &positions, &mut None)
        .expect("forward pass failed");

    assert_eq!(logits.dims(), f.shape.as_slice(), "logit shape mismatch");

    let ours: Vec<f32> = logits
        .flatten_all()
        .unwrap()
        .to_vec1::<f32>()
        .expect("logits are not f32");

    let diff = max_abs_diff(&ours, &f.reference);
    assert!(
        diff < 1e-5,
        "{name}: max abs logit difference vs HuggingFace reference is {diff}, expected < 1e-5"
    );
}

#[test]
fn parity_prefill_one_head_per_group() {
    assert_prefill_matches_reference("tiny_h4");
}

#[test]
fn parity_prefill_multiple_heads_per_group() {
    assert_prefill_matches_reference("tiny_h8");
}

/// Feeding tokens one at a time through the KV cache must reproduce the logits
/// of a single-shot prefill over the same tokens.
#[test]
fn parity_incremental_decode_matches_prefill() {
    let f = load("tiny_h4");
    let positions: Vec<usize> = (0..f.tokens.len()).collect();

    let prefill = f
        .model
        .forward_with_cache(&f.tokens, &positions, &mut None)
        .expect("prefill failed");
    let last = f.tokens.len() - 1;
    let prefill_last: Vec<f32> = prefill
        .get(0)
        .unwrap()
        .get(last)
        .unwrap()
        .to_vec1::<f32>()
        .unwrap();

    let mut cache: Option<Vec<KVCache>> = None;
    let mut step_last = Vec::new();
    for (i, &token) in f.tokens.iter().enumerate() {
        let logits = f
            .model
            .forward_with_cache(&[token], &[i], &mut cache)
            .expect("incremental step failed");
        step_last = logits
            .get(0)
            .unwrap()
            .get(0)
            .unwrap()
            .to_vec1::<f32>()
            .unwrap();
    }

    let diff = max_abs_diff(&step_last, &prefill_last);
    assert!(
        diff < 1e-5,
        "incremental decode diverges from prefill by {diff}, expected < 1e-5"
    );

    // Guard against the config being silently wrong in a way both paths share.
    assert_eq!(f.config.vocab_size, prefill_last.len());
}

/// `generate` returns generated tokens only. The `complete`, `repl` and server
/// paths slice on that assumption, so pin it here: they used to strip
/// `prompt.len()` tokens off the front, dropping output or panicking outright.
#[test]
fn generate_returns_generated_tokens_only() {
    let f = load("tiny_h4");
    let prompt = f.tokens.clone();
    let max_new_tokens = 5;

    // Greedy so the result does not depend on the RNG. The fixture vocabulary is
    // 256 tokens, so the real EOS id (50256) can never be produced and exactly
    // `max_new_tokens` tokens come back.
    let gen = CodeGenGenerator::new(f.model, 0.0, 1, 1.0, 1.0, max_new_tokens);
    let generated = gen.generate(&prompt).expect("generation failed");

    assert_eq!(
        generated.len(),
        max_new_tokens,
        "expected generated tokens only, got {} for a {}-token prompt",
        generated.len(),
        prompt.len()
    );
    assert!(
        generated
            .iter()
            .all(|t| (*t as usize) < f.config.vocab_size),
        "generated an out-of-vocabulary token: {generated:?}"
    );
}

/// The safetensors converter's output must load back to the same model.
/// Before `WeightLoader::load_from_safetensors` existed, nothing in the repo
/// could read what `examples/convert_codegen_to_safetensors.rs` wrote.
#[test]
fn safetensors_round_trip_matches_pytorch() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let device = Device::Cpu;

    let f = load("tiny_h4");
    let positions: Vec<usize> = (0..f.tokens.len()).collect();
    let from_pth = f
        .model
        .forward_with_cache(&f.tokens, &positions, &mut None)
        .unwrap()
        .flatten_all()
        .unwrap()
        .to_vec1::<f32>()
        .unwrap();

    // Same conversion the example performs: read every tensor, write safetensors.
    let pth = candle_core::pickle::PthTensors::new(dir.join("tiny_h4.pth"), None).unwrap();
    let names: Vec<String> = pth.tensor_infos().keys().cloned().collect();
    let tensors: std::collections::HashMap<String, candle_core::Tensor> = names
        .iter()
        .filter_map(|name| pth.get(name).ok().flatten().map(|t| (name.clone(), t)))
        .collect();
    assert!(!tensors.is_empty(), "no tensors read from the fixture");

    let tmp = tempfile::tempdir().unwrap();
    let out = tmp.path().join("model.safetensors");
    candle_core::safetensors::save(&tensors, &out).unwrap();

    let model = WeightLoader::load_from_safetensors(&out, &f.config, &device)
        .expect("failed to load converted safetensors");
    let from_st = model
        .forward_with_cache(&f.tokens, &positions, &mut None)
        .unwrap()
        .flatten_all()
        .unwrap()
        .to_vec1::<f32>()
        .unwrap();

    let diff = max_abs_diff(&from_st, &from_pth);
    assert!(
        diff < 1e-6,
        "safetensors round trip changed the logits by {diff}"
    );
}
